#!/bin/bash
#mkdir -p /home/babu/.ssh
#chmod 700 /home/babu/.ssh
#cp /authorized_keys /home/babu/.ssh/
#chmod 644 /home/babu/.ssh/authorized_keys
#mkdir /home/babu/data
#route
#hostname hplaptop
hostname
#traceroute github.com
#git clone git@github.com:tcbabu/data.git data
git clone $1  data
#scp  babu@github.com:BUILD/kgwrite/Readme data/
cd /home/babu/data
rm Readme.ps
ls -rtl ./
/kgwrite -oReadme.ps Readme
ls -rtl ./
#scp  Readme.ps babu@github.com:BUILD/kgwrite/
#git add Readme.ps
git config --global user.email "tcbabu@gmail.com"
git config --global user.name "tcbabu"

git commit -a -m "New Postscript File"
#git remote add origin git@github.com:tcbabu/data.git
git remote -v show
git push -u origin master
